"""
Code Generation Module
Generates Arduino, C++, and Python code from byte arrays
"""

import logging
from typing import List, Dict, Any
from .exceptions import ValidationError

logger = logging.getLogger(__name__)


class CodeGenerator:
    """Generates code in various programming languages"""

    @staticmethod
    def _sanitize_variable_name(filename: str, prefix: str = "") -> str:
        """
        Convert filename to valid variable name

        Args:
            filename: Original filename
            prefix: Optional prefix for variable name

        Returns:
            Sanitized variable name
        """
        # Remove extension and clean the name
        var_name = filename.split('.')[0]
        var_name = var_name.replace('-', '_').replace(' ', '_')
        var_name = ''.join(c if c.isalnum() or c == '_' else '_' for c in var_name)

        # Add prefix if provided
        if prefix:
            var_name = f"{prefix}_{var_name}"

        return var_name

    @staticmethod
    def generate_arduino_code(images_data: List[Dict[str, Any]], variable_prefix: str = "image",
                              include_dimensions: bool = True) -> str:
        """
        Generate Arduino-compatible C++ code

        Args:
            images_data: List of image conversion results
            variable_prefix: Prefix for variable names
            include_dimensions: Whether to include width/height constants

        Returns:
            Generated Arduino code as string
        """
        code_lines = [
            "// Generated by image2cpp",
            "// https://github.com/javl/image2cpp",
            "",
        ]

        for idx, img_data in enumerate(images_data):
            filename = img_data.get('filename', f'image_{idx}')
            var_name = CodeGenerator._sanitize_variable_name(filename, variable_prefix)

            width = img_data.get('width', 0)
            height = img_data.get('height', 0)
            byte_array = img_data.get('byte_array_raw', [])

            if include_dimensions:
                code_lines.append(f"// '{filename}', {width}x{height}px")

            code_lines.append(f"const unsigned char {var_name}[] PROGMEM = {{")

            # Format byte array with 16 bytes per line
            for i in range(0, len(byte_array), 16):
                chunk = byte_array[i:i+16]
                formatted_chunk = ', '.join(f'0x{byte:02X}' for byte in chunk)
                comma = "," if i + 16 < len(byte_array) else ""
                code_lines.append(f"  {formatted_chunk}{comma}")

            code_lines.append("};")

            if include_dimensions:
                code_lines.append(f"const int {var_name}_width = {width};")
                code_lines.append(f"const int {var_name}_height = {height};")

            code_lines.append("")

        # Add example usage
        code_lines.extend([
            "// Example usage with Adafruit GFX library:",
            "// display.drawBitmap(x, y, " + f"{variable_prefix}_yourimage" + ", width, height, color);",
            ""
        ])

        logger.info(f"Generated Arduino code for {len(images_data)} image(s)")
        return '\n'.join(code_lines)

    @staticmethod
    def generate_cpp_code(images_data: List[Dict[str, Any]], variable_prefix: str = "image",
                         include_dimensions: bool = True) -> str:
        """
        Generate standard C++ code

        Args:
            images_data: List of image conversion results
            variable_prefix: Prefix for variable names
            include_dimensions: Whether to include width/height constants

        Returns:
            Generated C++ code as string
        """
        code_lines = [
            "// Generated by image2cpp",
            "// https://github.com/javl/image2cpp",
            "",
            "#include <cstdint>",
            "",
        ]

        for idx, img_data in enumerate(images_data):
            filename = img_data.get('filename', f'image_{idx}')
            var_name = CodeGenerator._sanitize_variable_name(filename, variable_prefix)

            width = img_data.get('width', 0)
            height = img_data.get('height', 0)
            byte_array = img_data.get('byte_array_raw', [])

            if include_dimensions:
                code_lines.append(f"// '{filename}', {width}x{height}px")

            code_lines.append(f"const uint8_t {var_name}[] = {{")

            for i in range(0, len(byte_array), 16):
                chunk = byte_array[i:i+16]
                formatted_chunk = ', '.join(f'0x{byte:02X}' for byte in chunk)
                comma = "," if i + 16 < len(byte_array) else ""
                code_lines.append(f"  {formatted_chunk}{comma}")

            code_lines.append("};")

            if include_dimensions:
                code_lines.append(f"const int {var_name}_width = {width};")
                code_lines.append(f"const int {var_name}_height = {height};")

            code_lines.append("")

        logger.info(f"Generated C++ code for {len(images_data)} image(s)")
        return '\n'.join(code_lines)

    @staticmethod
    def generate_python_code(images_data: List[Dict[str, Any]], variable_prefix: str = "image",
                            include_dimensions: bool = True) -> str:
        """
        Generate Python code

        Args:
            images_data: List of image conversion results
            variable_prefix: Prefix for variable names
            include_dimensions: Whether to include width/height variables

        Returns:
            Generated Python code as string
        """
        code_lines = [
            "# Generated by image2cpp",
            "# https://github.com/javl/image2cpp",
            "",
        ]

        for idx, img_data in enumerate(images_data):
            filename = img_data.get('filename', f'image_{idx}')
            var_name = CodeGenerator._sanitize_variable_name(filename, variable_prefix)

            width = img_data.get('width', 0)
            height = img_data.get('height', 0)
            byte_array = img_data.get('byte_array_raw', [])

            if include_dimensions:
                code_lines.append(f"# '{filename}', {width}x{height}px")

            code_lines.append(f"{var_name} = [")

            for i in range(0, len(byte_array), 16):
                chunk = byte_array[i:i+16]
                formatted_chunk = ', '.join(f'0x{byte:02X}' for byte in chunk)
                comma = "," if i + 16 < len(byte_array) else ""
                code_lines.append(f"    {formatted_chunk}{comma}")

            code_lines.append("]")

            if include_dimensions:
                code_lines.append(f"{var_name}_width = {width}")
                code_lines.append(f"{var_name}_height = {height}")

            code_lines.append("")

        logger.info(f"Generated Python code for {len(images_data)} image(s)")
        return '\n'.join(code_lines)

    @staticmethod
    def generate_code(images_data: List[Dict[str, Any]], code_style: str = 'arduino',
                     variable_prefix: str = 'image', include_dimensions: bool = True) -> str:
        """
        Generate code in specified style

        Args:
            images_data: List of image conversion results
            code_style: 'arduino', 'cpp', or 'python'
            variable_prefix: Prefix for variable names
            include_dimensions: Whether to include dimensions

        Returns:
            Generated code as string

        Raises:
            ValidationError: If code_style is invalid
        """
        if code_style == 'arduino':
            return CodeGenerator.generate_arduino_code(images_data, variable_prefix, include_dimensions)
        elif code_style == 'cpp':
            return CodeGenerator.generate_cpp_code(images_data, variable_prefix, include_dimensions)
        elif code_style == 'python':
            return CodeGenerator.generate_python_code(images_data, variable_prefix, include_dimensions)
        else:
            raise ValidationError(f"Unsupported code style: {code_style}")
