"""
Image Processing Module
Handles image manipulation, conversion, and byte array generation
"""

import logging
import io
import base64
from typing import Dict, Tuple, List
from PIL import Image
from .exceptions import ImageProcessingError, ValidationError
from .validators import validate_image_dimensions, validate_compression_factor

logger = logging.getLogger(__name__)


class ImageProcessor:
    """Handles all image processing operations"""

    @staticmethod
    def apply_crop(image: Image.Image, crop_settings: Dict[str, int]) -> Image.Image:
        """
        Apply crop to image

        Args:
            image: PIL Image object
            crop_settings: Dictionary with crop values (top, right, bottom, left)

        Returns:
            Cropped PIL Image

        Raises:
            ImageProcessingError: If crop operation fails
        """
        try:
            width, height = image.size
            left = crop_settings['left']
            top = crop_settings['top']
            right = width - crop_settings['right']
            bottom = height - crop_settings['bottom']

            # Validate crop boundaries
            if left >= right or top >= bottom:
                raise ValidationError("Invalid crop settings: result would be empty or negative")

            if left < 0 or top < 0 or right > width or bottom > height:
                raise ValidationError("Crop settings exceed image boundaries")

            logger.debug(f"Applying crop: left={left}, top={top}, right={right}, bottom={bottom}")
            return image.crop((left, top, right, bottom))
        except ValidationError:
            raise
        except Exception as e:
            logger.error(f"Error applying crop: {e}")
            raise ImageProcessingError(f"Failed to crop image: {str(e)}")

    @staticmethod
    def compress_image(image: Image.Image, compression_factor: int) -> Image.Image:
        """
        Compress/resize image

        Args:
            image: PIL Image object
            compression_factor: Compression percentage (1-100)

        Returns:
            Compressed PIL Image

        Raises:
            ImageProcessingError: If compression fails
        """
        try:
            validate_compression_factor(compression_factor)

            if compression_factor < 100:
                width, height = image.size
                new_width = max(1, int(width * (compression_factor / 100)))
                new_height = max(1, int(height * (compression_factor / 100)))

                validate_image_dimensions(new_width, new_height)

                logger.debug(f"Compressing image: new dimensions=({new_width}, {new_height})")
                return image.resize((new_width, new_height), Image.LANCZOS)
            return image
        except ValidationError:
            raise
        except Exception as e:
            logger.error(f"Error compressing image: {e}")
            raise ImageProcessingError(f"Failed to compress image: {str(e)}")

    @staticmethod
    def image_to_byte_array(image: Image.Image, threshold: int = 128, mode: str = 'horizontal') -> List[int]:
        """
        Convert image to byte array

        Args:
            image: PIL Image object
            threshold: Binarization threshold (0-255)
            mode: Scan mode ('horizontal' or 'vertical')

        Returns:
            List of bytes representing the image

        Raises:
            ImageProcessingError: If conversion fails
        """
        try:
            width, height = image.size
            pixels = list(image.getdata())
            byte_array = []
            byte = 0
            bit_count = 0

            for y in range(height):
                for x in range(width):
                    if mode == 'horizontal':
                        pixel = pixels[y * width + x]
                    else:  # vertical
                        pixel = pixels[x * height + y]

                    # Convert to grayscale if RGB/RGBA
                    if isinstance(pixel, tuple):
                        pixel = sum(pixel[:3]) // 3

                    # Set bit if pixel is above threshold
                    if pixel > threshold:
                        byte |= (1 << (7 - bit_count))

                    bit_count += 1
                    if bit_count == 8:
                        byte_array.append(byte)
                        byte = 0
                        bit_count = 0

            # Add any remaining bits
            if bit_count > 0:
                byte_array.append(byte)

            logger.debug(f"Generated byte array: {len(byte_array)} bytes")
            return byte_array
        except Exception as e:
            logger.error(f"Error converting image to byte array: {e}")
            raise ImageProcessingError(f"Failed to convert image: {str(e)}")

    @staticmethod
    def byte_array_to_image(byte_array: List[int], width: int, height: int,
                           mode: str = 'horizontal') -> Image.Image:
        """
        Convert byte array back to image (for preview)

        Args:
            byte_array: List of bytes
            width: Image width
            height: Image height
            mode: Scan mode ('horizontal' or 'vertical')

        Returns:
            PIL Image object

        Raises:
            ImageProcessingError: If conversion fails
        """
        try:
            img = Image.new('1', (width, height))
            pixels = img.load()

            byte_index = 0
            bit_index = 0

            for y in range(height):
                for x in range(width):
                    if byte_index < len(byte_array):
                        if mode == 'horizontal':
                            if byte_array[byte_index] & (1 << (7 - bit_index)):
                                pixels[x, y] = 1
                            else:
                                pixels[x, y] = 0
                        else:  # vertical
                            if byte_array[byte_index] & (1 << (7 - bit_index)):
                                pixels[y, x] = 1
                            else:
                                pixels[y, x] = 0

                        bit_index += 1
                        if bit_index == 8:
                            byte_index += 1
                            bit_index = 0

            return img
        except Exception as e:
            logger.error(f"Error converting byte array to image: {e}")
            raise ImageProcessingError(f"Failed to create preview: {str(e)}")

    @staticmethod
    def generate_preview(image: Image.Image) -> str:
        """
        Generate base64-encoded preview image

        Args:
            image: PIL Image object

        Returns:
            Base64-encoded PNG image string

        Raises:
            ImageProcessingError: If preview generation fails
        """
        try:
            preview_buffer = io.BytesIO()
            image.save(preview_buffer, format='PNG')
            preview_base64 = base64.b64encode(preview_buffer.getvalue()).decode('utf-8')
            return preview_base64
        except Exception as e:
            logger.error(f"Error generating preview: {e}")
            raise ImageProcessingError(f"Failed to generate preview: {str(e)}")

    @staticmethod
    def process_image(image_data: bytes, threshold: int, mode: str,
                     crop_settings: Dict[str, int], compression_factor: int,
                     filename: str = "image") -> Dict:
        """
        Complete image processing pipeline

        Args:
            image_data: Raw image data bytes
            threshold: Binarization threshold
            mode: Scan mode
            crop_settings: Crop configuration
            compression_factor: Compression percentage
            filename: Original filename

        Returns:
            Dictionary containing conversion results

        Raises:
            ImageProcessingError: If processing fails
        """
        try:
            # Load and convert to grayscale
            image = Image.open(io.BytesIO(image_data)).convert('L')
            logger.debug(f"Processing {filename}: Original size {image.size}")

            # Apply transformations
            image = ImageProcessor.apply_crop(image, crop_settings)
            logger.debug(f"After crop: {image.size}")

            image = ImageProcessor.compress_image(image, compression_factor)
            logger.debug(f"After compression: {image.size}")

            # Convert to byte array
            byte_array = ImageProcessor.image_to_byte_array(image, threshold, mode)
            formatted_array = ', '.join(f'0x{byte:02X}' for byte in byte_array)

            # Generate preview
            preview_base64 = ImageProcessor.generate_preview(image)

            return {
                "filename": filename,
                "byte_array": formatted_array,
                "byte_array_raw": byte_array,
                "width": image.width,
                "height": image.height,
                "preview_image": preview_base64,
                "crop_settings": crop_settings
            }
        except Exception as e:
            logger.error(f"Error processing image {filename}: {e}")
            raise ImageProcessingError(f"Failed to process {filename}: {str(e)}")
